"""empty message

Revision ID: 03f6c84237de
Revises: 
Create Date: 2022-01-26 13:16:40.016915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f6c84237de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cupom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('desconto', sa.String(length=15), nullable=False),
    sa.Column('código', sa.String(length=20), nullable=False),
    sa.Column('forma_utilizacao', sa.String(length=100), nullable=False),
    sa.Column('campanha', sa.String(length=20), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_termino', sa.DateTime(), nullable=True),
    sa.Column('limite_usuarios', sa.Integer(), nullable=True),
    sa.Column('objetivo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('código')
    )
    op.create_table('encarte',
    sa.Column('marca', sa.String(length=30), nullable=False),
    sa.Column('tamanho', sa.String(length=20), nullable=False),
    sa.Column('preco_descontado', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_termino', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('marca', sa.String(length=30), nullable=False),
    sa.Column('tamanho', sa.String(length=20), nullable=False),
    sa.Column('preco_descontado', sa.Float(), nullable=True),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('subcategoria', sa.String(length=30), nullable=False),
    sa.Column('preco_normal', sa.Float(), nullable=False),
    sa.Column('lote', sa.String(length=40), nullable=False),
    sa.Column('validade', sa.DateTime(), nullable=False),
    sa.Column('custo', sa.Float(), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.Column('importado_nacional', sa.String(length=20), nullable=False),
    sa.Column('proibido_menor_idade', sa.Boolean(), nullable=True),
    sa.Column('alergenos', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lote')
    )
    op.create_table('association_product_encarte',
    sa.Column('id_encarte', sa.Integer(), nullable=True),
    sa.Column('id_produtos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_encarte'], ['encarte.id'], ),
    sa.ForeignKeyConstraint(['id_produtos'], ['produto.id'], )
    )
    op.create_table('carrinho',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modelo_entrega', sa.String(length=15), nullable=False),
    sa.Column('preco_entrega', sa.String(length=15), nullable=False),
    sa.Column('prazo_entrega', sa.String(length=15), nullable=False),
    sa.Column('quantidade_itens', sa.Integer(), nullable=False),
    sa.Column('preco_total', sa.Float(), nullable=False),
    sa.Column('data_pedido', sa.DateTime(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=15), nullable=False),
    sa.Column('agendamento_entrega', sa.DateTime(), nullable=True),
    sa.Column('id_cupom', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cupom'], ['cupom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_product_cart',
    sa.Column('id_carrinho', sa.Integer(), nullable=True),
    sa.Column('id_produtos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_carrinho'], ['carrinho.id'], ),
    sa.ForeignKeyConstraint(['id_produtos'], ['produto.id'], )
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pagamento_confirmado', sa.Boolean(), nullable=False),
    sa.Column('data_confirmacao_pagamento', sa.DateTime(), nullable=True),
    sa.Column('numero_parcelas', sa.Integer(), nullable=True),
    sa.Column('id_carrinho', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_carrinho'], ['carrinho.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=15), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('senha', sa.String(length=40), nullable=False),
    sa.Column('endereco', sa.String(length=80), nullable=False),
    sa.Column('cidade', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('cep', sa.String(length=15), nullable=False),
    sa.Column('ja_realizou_compra', sa.Boolean(), nullable=False),
    sa.Column('como_descobriu_site', sa.String(length=40), nullable=False),
    sa.Column('id_carrinho', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_carrinho'], ['carrinho.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cupom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cupom_id'], ['cupom.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('pedido')
    op.drop_table('association_product_cart')
    op.drop_table('carrinho')
    op.drop_table('association_product_encarte')
    op.drop_table('produto')
    op.drop_table('encarte')
    op.drop_table('cupom')
    # ### end Alembic commands ###
