"""empty message

Revision ID: c4f5949e41e5
Revises: cae993ba59c2
Create Date: 2022-01-26 16:02:35.279965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f5949e41e5'
down_revision = 'cae993ba59c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('encarte', 'marca')
    op.drop_column('encarte', 'preco_descontado')
    op.drop_column('encarte', 'tamanho')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encarte', sa.Column('tamanho', sa.VARCHAR(length=20), nullable=False))
    op.add_column('encarte', sa.Column('preco_descontado', sa.FLOAT(), nullable=True))
    op.add_column('encarte', sa.Column('marca', sa.VARCHAR(length=30), nullable=False))
    # ### end Alembic commands ###
