"""empty message

Revision ID: cae993ba59c2
Revises: 03f6c84237de
Create Date: 2022-01-26 15:23:57.543218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae993ba59c2'
down_revision = '03f6c84237de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cupom_código'), 'cupom', ['código'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cupom_código'), table_name='cupom')
    # ### end Alembic commands ###
